static const char *multipass_wrapper_prefix =
    "#version 330 core\n"
    "\n"
    "// Shadertoy compatibility uniforms\n"
    "uniform float iTime;\n"
    "uniform vec3 iResolution;\n"
    "uniform vec4 iMouse;\n"
    "// Shift from this window's gl_FragCoord to the virtual screen's. Zero\n"
    "// unless the wallpaper is spanned across several monitors.\n"
    "uniform vec2 iSpanOffset;\n"
    "uniform int iFrame;\n"
    "uniform float iTimeDelta;\n"
    "uniform float iFrameRate;\n"
    "uniform vec4 iDate;\n"
    "uniform float iSampleRate;\n"
    "\n"
    "// Texture samplers\n"
    "uniform sampler2D iChannel0;\n"
    "uniform sampler2D iChannel1;\n"
    "uniform sampler2D iChannel2;\n"
    "uniform sampler2D iChannel3;\n"
    "\n"
    "// Live-terminal source (CHANNEL_SOURCE_TERM). The cell record grid is an\n"
    "// INTEGER texture; the shader reads it via nwTerm(). Bind the matching\n"
    "// iChannelN to \"terminal\" so the engine points it at the cell texture,\n"
    "// then sample with nwTerm(iChannelN_as_usampler...). To keep call sites\n"
    "// simple we expose a dedicated integer sampler + the metadata uniforms.\n"
    "uniform highp usampler2D iTermCells;\n"
    "uniform highp usampler2D iTermChange; // R32UI: per-cell last-change ms\n"
    "uniform sampler2D iTermAtlas;\n"
    "uniform sampler2D iTermColorAtlas;\n"
    "uniform vec4 iTermInfo;       // cols, rows, cellW, cellH\n"
    "uniform vec2 iTermAtlasSize;  // atlas texel w, h\n"
    "uniform vec3 iTermCursor;     // cursorX, cursorY, visible\n"
    "uniform vec4 iTermCursorPrev; // prevX, prevY, moveTime, (unused)\n"
    "uniform vec4 iTermFX;         // bloom, scanline, crt-curve, chromatic\n"
    "uniform vec2 iTermFade;       // x = change-fade intensity, y = now (ms)\n"
    "#define NW_HAS_ITERMFX 1\n"
    "\n"
    "// Channel resolutions\n"
    "uniform vec3 iChannelResolution[4];\n"
    "uniform float iChannelTime[4];\n"
    "\n"
    "// --- Shadertoy / GLSL-ES compatibility shims ---\n"
    "// Legacy ES sampling builtins -> desktop core equivalents. Defined as\n"
    "// macros so we never have to rewrite call sites in the user source.\n"
    "#define texture2D texture\n"
    "#define texture2DLod textureLod\n"
    "#define texture2DProj textureProj\n"
    "#define textureCube texture\n"
    "#define textureCubeLod textureLod\n"
    "// Legacy global-time alias used by older Shadertoy shaders.\n"
    "#define iGlobalTime iTime\n"
    "\n"
    "// Output\n"
    "out vec4 fragColor;\n"
    "\n";

static const char *multipass_wrapper_suffix =
    "\n"
    "void main() {\n"
    "    mainImage(fragColor, gl_FragCoord.xy + iSpanOffset);\n"
    "}\n";
