#define NEOWALL_VERSION_STRING "0.7.1"
#define NEOWALL_VERSION_MAJOR 0
#define NEOWALL_VERSION_MINOR 7
#define NEOWALL_VERSION_PATCH 1
#define NEOWALL_VERSION_NUMBER (NEOWALL_VERSION_MAJOR * 10000 + NEOWALL_VERSION_MINOR * 100 + NEOWALL_VERSION_PATCH)
